image: docker.io/labrobotica/labrobotica:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

build-package:
  stage: build
  script:
    - apt update || apt -y install ca-certificates && apt update
    - apt -y install iri-iriutils-dev iri-comm-dev
    - mkdir -pv build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPACK_PACKAGE_VERSION=$CI_COMMIT_TAG ..
    - ls ..
    - make package -j $(nproc)
    
  artifacts:
    paths:
      - build/*.deb
    expire_in: 2 weeks
  only:
    - tags
    
update_repo:
  stage: deploy
  script:
    - cd build
    - "scp -i /root/.ssh/iriLabKeyNopwd -r *segway-rmp-200*.deb irilabo@labrepo.iri.upc.edu:packages/"
    - "ssh irilabo@labrepo.iri.upc.edu -i /root/.ssh/iriLabKeyNopwd -tt /home/irilabo/repo_scripts/update_repo.sh segway-rmp-200 $(lsb_release -cs)"
  only:
    - tags
    
